cnieg/helm-charts

- charts/gantt/.helmignore
- charts/gantt/Chart.yaml
- charts/gantt/templates/NOTES.txt
- charts/gantt/templates/_helpers.tpl
- charts/gantt/templates/deployment.yaml
- charts/gantt/templates/ingress.yaml
- charts/gantt/templates/pvc.yaml
- charts/gantt/templates/service.yaml
- charts/gantt/templates/tests/test-connection.yaml
- charts/gantt/values.yaml
Signed-off-by: Thomah <5090230+Thomah@users.noreply.github.com>
> [gantt] Initial version

- charts/proxy-relay/.helmignore
- charts/proxy-relay/Chart.yaml
- charts/proxy-relay/templates/NOTES.txt
- charts/proxy-relay/templates/_helpers.tpl
- charts/proxy-relay/templates/configmap.yaml
- charts/proxy-relay/templates/deployment.yaml
- charts/proxy-relay/templates/ingress.yaml
- charts/proxy-relay/templates/service.yaml
- charts/proxy-relay/templates/tests/test-connection.yaml
- charts/proxy-relay/values.yaml
> Init chart proxy-relay

- charts/h2-database/Chart.yaml
- charts/h2-database/templates/_helpers.tpl
- charts/h2-database/templates/deployment.yaml
- charts/h2-database/templates/ingress.yaml
- charts/h2-database/templates/service.yaml
- charts/h2-database/values.yaml
> [h2-database]Fix #5 reference cnieg domain

- charts/proxy-relay/Chart.yaml
- charts/proxy-relay/ci/ci-values.yaml
- charts/proxy-relay/templates/ingress.yaml
- charts/proxy-relay/values.yaml
> #7 : Ingress indent labels & add default path for ingress

- charts/pulsar/Chart.yaml
- charts/pulsar/templates/pulsar-manager-ingress.yaml
- charts/pulsar/values.yaml
> add ingress manifest and values to expose pulsar_manager

- charts/pulsar/Chart.yaml
- charts/pulsar/values.yaml
> Fix ingress destination port to service

- charts/pulsar/Chart.yaml
- charts/pulsar/templates/pulsar-manager-admin-secret.yaml
- charts/pulsar/templates/pulsar-manager-deployment.yaml
- charts/pulsar/values.yaml
> [pulsar] Add ability to specify external secret for manager

- charts/elastic-stack/.helmignore
- charts/elastic-stack/Chart.yaml
- charts/elastic-stack/ci/ci-values.yaml
- charts/elastic-stack/requirements.lock
- charts/elastic-stack/requirements.yaml
- charts/elastic-stack/values.yaml
- ct.yaml
> feat(elastic-stack) : init repo

- charts/elastic-stack/Chart.yaml
Add sources in Chart.yaml
Add email adresse for maintainers
> fix(elastic-stack): Chart.yaml ref to icon

- .gitignore
- charts/maildev/.helmignore
- charts/maildev/Chart.yaml
- charts/maildev/templates/NOTES.txt
- charts/maildev/templates/_helpers.tpl
- charts/maildev/templates/cron.yaml
- charts/maildev/templates/deployment.yaml
- charts/maildev/templates/ingress.yaml
- charts/maildev/templates/pvc.yaml
- charts/maildev/templates/service-http.yaml
- charts/maildev/templates/service-smtp.yaml
- charts/maildev/templates/tests/test-connection.yaml
- charts/maildev/values.yaml
> feat(maildev): initialisation du repo

- charts/maildev/Chart.yaml
- charts/maildev/values.yaml
> [maildev]: bump version docker image

- .github/workflows/helm.yaml
- charts/elastic-stack/Chart.yaml
- charts/elastic-stack/ci/ci-values.yaml
- charts/elastic-stack/requirements.lock
- charts/elastic-stack/requirements.yaml
> [elastic-stack]: bump dependencies elastic to 7.7.0

- charts/clamapi/.helmignore
- charts/clamapi/Chart.yaml
- charts/clamapi/requirements.lock
- charts/clamapi/requirements.yaml
- charts/clamapi/templates/NOTES.txt
- charts/clamapi/templates/_helpers.tpl
- charts/clamapi/templates/deployment.yaml
- charts/clamapi/templates/horizontal-pod-autoscaler.yaml
- charts/clamapi/templates/ingress.yaml
- charts/clamapi/templates/pod-disruption-budget.yaml
- charts/clamapi/templates/service.yaml
- charts/clamapi/templates/tests/test-connection.yaml
- charts/clamapi/values.yaml
- ct.yaml
> [clamapi]: init chart

- charts/pulsar/Chart.yaml
- charts/pulsar/values.yaml
> [pulsar]: Fix set limit memory toolset

- charts/pulsar/Chart.yaml
- charts/pulsar/values.yaml
> [pulsar]: Fix set limit memory recovery

- charts/clamapi/Chart.yaml
- charts/clamapi/values.yaml
> [clamapi]:Bump app version

- charts/castlemock/Chart.yaml
- charts/castlemock/templates/deployment.yaml
- charts/castlemock/templates/ingress.yaml
- charts/castlemock/templates/pvc.yaml
- charts/castlemock/values.yaml
- persistence not used by chart
- storageClass
- pvc label indentation
- add javaOpts property for jvm usage
> fix: persistence usage in chart

- charts/castlemock/Chart.yaml
- charts/castlemock/templates/pvc.yaml
> [castlemock]: fix indent in labels for pvc

- charts/castlemock/Chart.yaml
- charts/castlemock/templates/deployment.yaml
- charts/castlemock/values.yaml
> fix(castlemock): #31 externalize livenessConf

- charts/castlemock/Chart.yaml
- charts/castlemock/templates/pvc.yaml
- charts/castlemock/values.yaml
- ct.yaml
Signed-off-by: adcg <guillaume.audic@cnieg.fr>
> feat(castlemock): Add annotations value for pvc

- charts/dependency-track/Chart.yaml
Signed-off-by: adcg <guillaume.audic@cnieg.fr>
> feat(dependency-track): Upgrade apiVersion helm to v2

- charts/clamapi/Chart.yaml
- charts/clamapi/requirements.lock
- charts/clamapi/requirements.yaml
- charts/clamapi/templates/deployment.yaml
- charts/clamapi/values.yaml
- ct.yaml
Hi @arnou and @audig,
I needed to increase the servlets max upload file size.
But I think this comes handy in many situations.
Best regards
Alex
> [clamapi] Add custom-env property and update requirements

- charts/maildev/Chart.yaml
- charts/maildev/templates/deployment.yaml
- charts/maildev/values.yaml
**Chart:**
maildev
**What this PR does / why we need it:**
Add pod annotation configuration
> Add pod annotation configuration

- charts/maildev/Chart.yaml
- charts/maildev/templates/cron.yaml
- charts/maildev/templates/ingress.yaml
- charts/maildev/values.yaml
Works cleanly. the ingress was previously broken entirely
> 2021-11 update api versions and ingress

- charts/castlemock/Chart.yaml
fix #66 the castlemock's maintainers remove old images
> Use latest docker image version

- charts/passbolt/Chart.yaml
- charts/passbolt/README.md
- charts/passbolt/templates/deployment.yaml
- charts/passbolt/templates/ingress.yaml
- charts/passbolt/values.yaml
Passbolt chart changes:
- Email configuration with env variables in deployment
- Upgrade ingress to new kubernetes api version
- Readme update for passbolt
> #70 - email configuration

- artifacthub-repo.yml
reference https://artifacthub.io/control-panel/repositories?page=1
> fix: avoid scan errors from deleted images

- charts/passbolt/Chart.yaml
- charts/passbolt/templates/_helpers.tpl
- charts/passbolt/templates/deployment.yaml
- charts/passbolt/templates/serviceaccount.yaml
- charts/passbolt/values.yaml
> [FEAT] added ServiceAccount

- charts/passbolt/Chart.yaml
- charts/passbolt/templates/ingress.yaml
- charts/passbolt/templates/pdb.yaml
The condition to evaluate the version of kubernetes is wrong, this causes an invalid rendering on clusters with newer kubernetes version (e.g. 1.24)
> fix ingress rendering

- charts/clamapi/Chart.yaml
- charts/clamapi/requirements.lock
- charts/clamapi/requirements.yaml
- charts/clamapi/templates/horizontal-pod-autoscaler.yaml
Use apiVersion: autoscaling/v2
Chart in 2.0.4
> feat(clamapi): update HorizontalPodAutoscaler
